name: 'Change Log Updater'
description: 'Updates My Pro Plugin's Change Log To Its Docs Repository In Github'
author: 'varunsridharan'
branding:
  icon: 'message-square'
  color: 'gray-dark'
inputs:
  docs_repo_link:
    description: 'Documentation Github Repository Link'
  docs_change_log_file:
    default: 'change-log.md'
    description: 'Documentation Github Repository Link'
  local_change_log_file:
    default: 'CHANGELOG.md'
    description: 'Documentation Github Repository Link'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docs_repo_link }}
    - ${{ inputs.docs_change_log_file }}
    - ${{ inputs.local_change_log_file }}
