name: 'Change Log Updater'
description: 'Updates My Pro Plugins Change Log To Its Docs Repository In Github'
author: 'varunsridharan'
branding:
  icon: 'message-square'
  color: 'gray-dark'
inputs:
  repo_name:
    description: 'Documentation Github Repository Link'
  remote_file:
    default: 'change-log.md'
    description: 'Documentation Github Repository Link'
  local_file:
    default: 'CHANGELOG.md'
    description: 'Documentation Github Repository Link'
  github_token:
    description: 'Github Personal Access Token'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_name }}
    - ${{ inputs.remote_file }}
    - ${{ inputs.local_file }}
    - ${{ inputs.github_token }}
